name: 'Terraform'

on: [push, pull_request]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Format'
        run: terraform fmt -check -diff
        continue-on-error: true

      - name: 'Terraform Validate'
        env:
          AWS_REGION: 'us-east-1'
        run: |
          terraform init
          terraform validate -no-color

      - name: "tfsec - Security Scan"
        uses: triat/terraform-security-scan@v2.2.3
        with:
          tfsec_actions_comment: false
